name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ["Test and Lint"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download build artifacts
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: test.yml
        name: build
        path: dist
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        publish_branch: gh-pages
        commit_message: "Deploy: ${{ github.event.workflow_run.head_commit.message }}" 